AWSTemplateFormatVersion: '2010-09-09'
Description: MediaWiki IAM policies
Parameters:
  BucketName:
    Type: String
    Description: Upload bucket name
  SendIdentity:
    Type: String
    Description: Send identity ARN
Resources:
  AccessBucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Access to MediaWiki upload bucket
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetObjectTagging
              - s3:PutObject
              - s3:PutObjectTagging
              - s3:PutObjectAcl
              - s3:DeleteObject
              - s3:DeleteObjectTagging
            Resource:
              - !Sub "arn:aws:s3:::${BucketName}"
              - !Sub "arn:aws:s3:::${BucketName}/*"
  SendEmailPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Send MediaWiki email
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
              - ses:SendBulkEmail
              - ses:SendTemplatedEmail
              - ses:SendBulkTemplatedEmail
            Resource:
              - !Ref SendIdentity
              - !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:template/*"
